package com.synchrony.secure.media.api.model;

import jakarta.persistence.*;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;

/**
 * Entity class representing a user in the system.
 * This class is mapped to a database table using JPA annotations.
 */
@Entity
@Data
public class Users {

    /**
     * The unique identifier for the user.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY)
    private Long id;

    /**
     * The unique username of the user.
     * This field is marked as unique in the database.
     */
    @Column(unique = true)
    private String username;

    /**
     * The password of the user.
     * This field stores the user's hashed password.
     */
    private String password;

    /**
     * The email address of the user.
     */
    private String email;

    /**
     * A list of image URLs associated with the user.
     * This field is stored as a collection in a separate table.
     * The length of each URL is limited to 1000 characters.
     */
    @ElementCollection
    @CollectionTable(name = "users_image_urls")
    @Column(name = "image_urls", length = 1000) // Increase VARCHAR size
    private List<String> imageUrls = new ArrayList<>();
}