name: CI/CD for SynchronySecureMediaAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Run Unit Tests
      run: mvn test

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: spring-boot-app
        path: target/*.jar